# Learn more about this Gitpod configuration file in the documentation at https://www.gitpod.io/docs/configuration

ports:
  - name: Website preview
    port: 5173
    onOpen: open-preview

# List the start-up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks
tasks:
  - name: Install Dependencies and Start Dev Server
    init: npm install
    command: npm run dev

vscode:
  extensions:
    - svelte.svelte-vscode
